apiVersion: v1
kind: Service
metadata:
  name: medical-transcription
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: medical-transcription 